package model;
// Generated Jun 17, 2016 11:36:27 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Components generated by hbm2java
 */
public class Components implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3440145261051777722L;
	private Integer id;
	private JobStatus jobStatus;
	private Job jobs;
	private User users;
	private String name;
	private String description;
	private String notes;
	private Date date;
	private Set materialsUsages = new HashSet(0);
	private Set operationsLogs = new HashSet(0);

	public Components() {
	}

	public Components(JobStatus jobStatus, Job jobs, User users, String name, Date date) {
		this.jobStatus = jobStatus;
		this.jobs = jobs;
		this.users = users;
		this.name = name;
		this.date = date;
	}

	public Components(JobStatus jobStatus, Job jobs, User users, String name, String description, String notes,
			Date date, Set materialsUsages, Set operationsLogs) {
		this.jobStatus = jobStatus;
		this.jobs = jobs;
		this.users = users;
		this.name = name;
		this.description = description;
		this.notes = notes;
		this.date = date;
		this.materialsUsages = materialsUsages;
		this.operationsLogs = operationsLogs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public JobStatus getJobStatus() {
		return this.jobStatus;
	}

	public void setJobStatus(JobStatus jobStatus) {
		this.jobStatus = jobStatus;
	}

	public Job getJobs() {
		return this.jobs;
	}

	public void setJobs(Job jobs) {
		this.jobs = jobs;
	}

	public User getUsers() {
		return this.users;
	}

	public void setUsers(User users) {
		this.users = users;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Set getMaterialsUsages() {
		return this.materialsUsages;
	}

	public void setMaterialsUsages(Set materialsUsages) {
		this.materialsUsages = materialsUsages;
	}

	public Set getOperationsLogs() {
		return this.operationsLogs;
	}

	public void setOperationsLogs(Set operationsLogs) {
		this.operationsLogs = operationsLogs;
	}

}
