package model;
// default package
// Generated Jun 17, 2016 11:36:27 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Customers generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Integer id;
	private String name;
	private String address1;
	private String address2;
	private String address3;
	private String suburb;
	private String state;
	private String postcode;
	private Set jobses = new HashSet(0);
	private Set customerContactses = new HashSet(0);

	public Customer() {
	}

	public Customer(String name) {
		this.name = name;
	}

	public Customer(String name, String address1, String address2, String address3, String suburb, String state,
			String postcode, Set jobses, Set customerContactses) {
		this.name = name;
		this.address1 = address1;
		this.address2 = address2;
		this.address3 = address3;
		this.suburb = suburb;
		this.state = state;
		this.postcode = postcode;
		this.jobses = jobses;
		this.customerContactses = customerContactses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getAddress3() {
		return this.address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	public String getSuburb() {
		return this.suburb;
	}

	public void setSuburb(String suburb) {
		this.suburb = suburb;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public Set getJobses() {
		return this.jobses;
	}

	public void setJobses(Set jobses) {
		this.jobses = jobses;
	}

	public Set getCustomerContactses() {
		return this.customerContactses;
	}

	public void setCustomerContactses(Set customerContactses) {
		this.customerContactses = customerContactses;
	}

}
