package model;
import java.util.HashSet;
import java.util.Set;

/**
 * JobStatus generated by hbm2java
 */
public class JobStatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String description;
	private Set componentses = new HashSet(0);
	private Set jobses = new HashSet(0);

	public JobStatus() {
	}

	public JobStatus(String description) {
		this.description = description;
	}

	public JobStatus(String description, Set componentses, Set jobses) {
		this.description = description;
		this.componentses = componentses;
		this.jobses = jobses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getComponentses() {
		return this.componentses;
	}

	public void setComponentses(Set componentses) {
		this.componentses = componentses;
	}

	public Set getJobses() {
		return this.jobses;
	}

	public void setJobses(Set jobses) {
		this.jobses = jobses;
	}

}
