package model;
// Generated Jun 17, 2016 11:36:27 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * MaterialTypes generated by hbm2java
 */
public class MaterialTypes implements java.io.Serializable {

	private Integer id;
	private String description;
	private String unitOfMeasure;
	private Set defaultOperationses = new HashSet(0);
	private Set materialses = new HashSet(0);

	public MaterialTypes() {
	}

	public MaterialTypes(String unitOfMeasure) {
		this.unitOfMeasure = unitOfMeasure;
	}

	public MaterialTypes(String description, String unitOfMeasure, Set defaultOperationses, Set materialses) {
		this.description = description;
		this.unitOfMeasure = unitOfMeasure;
		this.defaultOperationses = defaultOperationses;
		this.materialses = materialses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUnitOfMeasure() {
		return this.unitOfMeasure;
	}

	public void setUnitOfMeasure(String unitOfMeasure) {
		this.unitOfMeasure = unitOfMeasure;
	}

	public Set getDefaultOperationses() {
		return this.defaultOperationses;
	}

	public void setDefaultOperationses(Set defaultOperationses) {
		this.defaultOperationses = defaultOperationses;
	}

	public Set getMaterialses() {
		return this.materialses;
	}

	public void setMaterialses(Set materialses) {
		this.materialses = materialses;
	}

}
