package model;
// Generated Jun 17, 2016 11:36:27 AM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Materials generated by hbm2java
 */
public class Materials implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private MaterialTypes materialTypes;
	private String description;
	private BigDecimal costPrice;
	private int qtyOnHand;
	private BigDecimal markupPercent;
	private String salePrice;
	private Set materialsUsages = new HashSet(0);
	private Set purchaseOrderLineItemses = new HashSet(0);
	
	private  int materialTypesId;
	

	public Materials() {
	}

	public Materials(MaterialTypes materialTypes, BigDecimal costPrice, int qtyOnHand, BigDecimal markupPercent) {
		this.materialTypes = materialTypes;
		this.costPrice = costPrice;
		this.qtyOnHand = qtyOnHand;
		this.markupPercent = markupPercent;
	}

	public Materials(MaterialTypes materialTypes, String description, BigDecimal costPrice, int qtyOnHand,
			BigDecimal markupPercent, String salePrice, Set materialsUsages, Set purchaseOrderLineItemses) {
		this.materialTypes = materialTypes;
		this.description = description;
		this.costPrice = costPrice;
		this.qtyOnHand = qtyOnHand;
		this.markupPercent = markupPercent;
		this.salePrice = salePrice;
		this.materialsUsages = materialsUsages;
		this.purchaseOrderLineItemses = purchaseOrderLineItemses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public MaterialTypes getMaterialTypes() {
		return this.materialTypes;
	}

	public void setMaterialTypes(MaterialTypes materialTypes) {
		this.materialTypes = materialTypes;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BigDecimal getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(BigDecimal costPrice) {
		this.costPrice = costPrice;
	}

	public int getQtyOnHand() {
		return this.qtyOnHand;
	}

	public void setQtyOnHand(int qtyOnHand) {
		this.qtyOnHand = qtyOnHand;
	}

	public BigDecimal getMarkupPercent() {
		return this.markupPercent;
	}

	public void setMarkupPercent(BigDecimal markupPercent) {
		this.markupPercent = markupPercent;
	}

	public String getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(String salePrice) {
		this.salePrice = salePrice;
	}

	public Set getMaterialsUsages() {
		return this.materialsUsages;
	}

	public void setMaterialsUsages(Set materialsUsages) {
		this.materialsUsages = materialsUsages;
	}

	public Set getPurchaseOrderLineItemses() {
		return this.purchaseOrderLineItemses;
	}

	public void setPurchaseOrderLineItemses(Set purchaseOrderLineItemses) {
		this.purchaseOrderLineItemses = purchaseOrderLineItemses;
	}

	/**
	 * @return the materialTypesId
	 */
	public int getMaterialTypesId() {
		return materialTypesId;
	}

	/**
	 * @param materialTypesId the materialTypesId to set
	 */
	public void setMaterialTypesId(int materialTypesId) {
		this.materialTypesId = materialTypesId;
	}

}
