package model;
// Generated Jun 17, 2016 11:36:27 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * OperationTypes generated by hbm2java
 */
public class OperationTypes implements java.io.Serializable {

	private Integer id;
	private String description;
	private String unitOfMeasure;
	private Set operationses = new HashSet(0);

	public OperationTypes() {
	}

	public OperationTypes(String description, String unitOfMeasure) {
		this.description = description;
		this.unitOfMeasure = unitOfMeasure;
	}

	public OperationTypes(String description, String unitOfMeasure, Set operationses) {
		this.description = description;
		this.unitOfMeasure = unitOfMeasure;
		this.operationses = operationses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUnitOfMeasure() {
		return this.unitOfMeasure;
	}

	public void setUnitOfMeasure(String unitOfMeasure) {
		this.unitOfMeasure = unitOfMeasure;
	}

	public Set getOperationses() {
		return this.operationses;
	}

	public void setOperationses(Set operationses) {
		this.operationses = operationses;
	}

}
