package model;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Operations generated by hbm2java
 */
public class Operations implements java.io.Serializable {

	private Integer id;
	private OperationTypes operationTypes;
	private String description;
	private BigDecimal costPrice;
	private BigDecimal markupPercent;
	private String salePrice;
	private Set defaultOperationses = new HashSet(0);
	private Set operationsLogs = new HashSet(0);

	public Operations() {
	}

	public Operations(OperationTypes operationTypes, BigDecimal costPrice, BigDecimal markupPercent) {
		this.operationTypes = operationTypes;
		this.costPrice = costPrice;
		this.markupPercent = markupPercent;
	}

	public Operations(OperationTypes operationTypes, String description, BigDecimal costPrice, BigDecimal markupPercent,
			String salePrice, Set defaultOperationses, Set operationsLogs) {
		this.operationTypes = operationTypes;
		this.description = description;
		this.costPrice = costPrice;
		this.markupPercent = markupPercent;
		this.salePrice = salePrice;
		this.defaultOperationses = defaultOperationses;
		this.operationsLogs = operationsLogs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public OperationTypes getOperationTypes() {
		return this.operationTypes;
	}

	public void setOperationTypes(OperationTypes operationTypes) {
		this.operationTypes = operationTypes;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BigDecimal getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(BigDecimal costPrice) {
		this.costPrice = costPrice;
	}

	public BigDecimal getMarkupPercent() {
		return this.markupPercent;
	}

	public void setMarkupPercent(BigDecimal markupPercent) {
		this.markupPercent = markupPercent;
	}

	public String getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(String salePrice) {
		this.salePrice = salePrice;
	}

	public Set getDefaultOperationses() {
		return this.defaultOperationses;
	}

	public void setDefaultOperationses(Set defaultOperationses) {
		this.defaultOperationses = defaultOperationses;
	}

	public Set getOperationsLogs() {
		return this.operationsLogs;
	}

	public void setOperationsLogs(Set operationsLogs) {
		this.operationsLogs = operationsLogs;
	}

}
