package model;
// Generated Jun 17, 2016 11:36:27 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * PurchaseOrderStatus generated by hbm2java
 */
public class PurchaseOrderStatus implements java.io.Serializable {

	private Integer id;
	private String description;
	private Set purchaseOrderses = new HashSet(0);

	public PurchaseOrderStatus() {
	}

	public PurchaseOrderStatus(String description) {
		this.description = description;
	}

	public PurchaseOrderStatus(String description, Set purchaseOrderses) {
		this.description = description;
		this.purchaseOrderses = purchaseOrderses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getPurchaseOrderses() {
		return this.purchaseOrderses;
	}

	public void setPurchaseOrderses(Set purchaseOrderses) {
		this.purchaseOrderses = purchaseOrderses;
	}

}
