package model;
// Generated Jun 17, 2016 11:36:27 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PurchaseOrders generated by hbm2java
 */
public class PurchaseOrders implements java.io.Serializable {

	private Integer id;
	private PurchaseOrderStatus purchaseOrderStatus;
	private Suppliers suppliers;
	private Date date;
	private String notes;
	private Set purchaseOrderLineItemses = new HashSet(0);

	public PurchaseOrders() {
	}

	public PurchaseOrders(PurchaseOrderStatus purchaseOrderStatus, Suppliers suppliers, Date date) {
		this.purchaseOrderStatus = purchaseOrderStatus;
		this.suppliers = suppliers;
		this.date = date;
	}

	public PurchaseOrders(PurchaseOrderStatus purchaseOrderStatus, Suppliers suppliers, Date date, String notes,
			Set purchaseOrderLineItemses) {
		this.purchaseOrderStatus = purchaseOrderStatus;
		this.suppliers = suppliers;
		this.date = date;
		this.notes = notes;
		this.purchaseOrderLineItemses = purchaseOrderLineItemses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public PurchaseOrderStatus getPurchaseOrderStatus() {
		return this.purchaseOrderStatus;
	}

	public void setPurchaseOrderStatus(PurchaseOrderStatus purchaseOrderStatus) {
		this.purchaseOrderStatus = purchaseOrderStatus;
	}

	public Suppliers getSuppliers() {
		return this.suppliers;
	}

	public void setSuppliers(Suppliers suppliers) {
		this.suppliers = suppliers;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Set getPurchaseOrderLineItemses() {
		return this.purchaseOrderLineItemses;
	}

	public void setPurchaseOrderLineItemses(Set purchaseOrderLineItemses) {
		this.purchaseOrderLineItemses = purchaseOrderLineItemses;
	}

}
