package model;
// Generated Jun 17, 2016 11:36:27 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Suppliers generated by hbm2java
 */
public class Suppliers implements java.io.Serializable {

	private Integer id;
	private String name;
	private String address1;
	private String address2;
	private String address3;
	private String notes;
	private Set purchaseOrderses = new HashSet(0);
	private Set supplierContactses = new HashSet(0);

	public Suppliers() {
	}

	public Suppliers(String name) {
		this.name = name;
	}

	public Suppliers(String name, String address1, String address2, String address3, String notes, Set purchaseOrderses,
			Set supplierContactses) {
		this.name = name;
		this.address1 = address1;
		this.address2 = address2;
		this.address3 = address3;
		this.notes = notes;
		this.purchaseOrderses = purchaseOrderses;
		this.supplierContactses = supplierContactses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getAddress3() {
		return this.address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Set getPurchaseOrderses() {
		return this.purchaseOrderses;
	}

	public void setPurchaseOrderses(Set purchaseOrderses) {
		this.purchaseOrderses = purchaseOrderses;
	}

	public Set getSupplierContactses() {
		return this.supplierContactses;
	}

	public void setSupplierContactses(Set supplierContactses) {
		this.supplierContactses = supplierContactses;
	}

}
