package model;
// Generated Jun 17, 2016 11:36:27 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * UserTypes generated by hbm2java
 */
public class UserTypes implements java.io.Serializable {

	private Integer id;
	private String description;
	private Set userses = new HashSet(0);

	public UserTypes() {
	}

	public UserTypes(String description) {
		this.description = description;
	}

	public UserTypes(String description, Set userses) {
		this.description = description;
		this.userses = userses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
