-- MySQL Script generated by MySQL Workbench
-- Fri Mar 11 15:21:14 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_types` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `user_types_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_user_types1_idx` (`user_types_id` ASC),
  CONSTRAINT `fk_users_user_types1`
    FOREIGN KEY (`user_types_id`)
    REFERENCES `mydb`.`user_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address1` VARCHAR(45) NULL,
  `address2` VARCHAR(45) NULL,
  `address3` VARCHAR(45) NULL,
  `suburb` VARCHAR(25) NULL,
  `state` VARCHAR(3) NULL,
  `postcode` VARCHAR(4) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`job_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`job_status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jobs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `job_name` VARCHAR(45) NOT NULL,
  `date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date job entered',
  `customer_id` INT NOT NULL,
  `notes` MEDIUMTEXT NULL,
  `users_id` INT UNSIGNED NOT NULL COMMENT 'Job entered by this user',
  `job_status_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_job_customer_idx` (`customer_id` ASC),
  INDEX `fk_job_users1_idx` (`users_id` ASC),
  INDEX `fk_jobs_job_status1_idx` (`job_status_id` ASC),
  CONSTRAINT `fk_job_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jobs_job_status1`
    FOREIGN KEY (`job_status_id`)
    REFERENCES `mydb`.`job_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`components` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `job_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `notes` MEDIUMTEXT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date entered',
  `users_id` INT UNSIGNED NOT NULL COMMENT 'entered by user',
  `job_status_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_component_job_idx` (`job_id` ASC),
  INDEX `fk_components_users1_idx` (`users_id` ASC),
  INDEX `fk_components_job_status1_idx` (`job_status_id` ASC),
  CONSTRAINT `fk_component_job`
    FOREIGN KEY (`job_id`)
    REFERENCES `mydb`.`jobs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_components_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_components_job_status1`
    FOREIGN KEY (`job_status_id`)
    REFERENCES `mydb`.`job_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`material_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`material_types` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  `UnitOfMeasure` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materials` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  `cost_price` DECIMAL(6,2) NOT NULL COMMENT 'price/ 1 * Unit of Measure',
  `qty_on_hand` INT NOT NULL DEFAULT 0,
  `material_types_id` INT NOT NULL,
  `markup_percent` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `sale_price` VARCHAR(45) GENERATED ALWAYS AS (cost_price * ( 1+ (markup_percent / 100))),
  PRIMARY KEY (`id`),
  INDEX `fk_materials_material_types1_idx` (`material_types_id` ASC),
  CONSTRAINT `fk_materials_material_types1`
    FOREIGN KEY (`material_types_id`)
    REFERENCES `mydb`.`material_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`materials_usage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materials_usage` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL DEFAULT CURRENT_DATETIME,
  `qty` INT UNSIGNED NOT NULL,
  `component_id` INT UNSIGNED NOT NULL,
  `materials_id` INT UNSIGNED NOT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_materials_usage_component1_idx` (`component_id` ASC),
  INDEX `fk_materials_usage_materials1_idx` (`materials_id` ASC),
  INDEX `fk_materials_usage_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_materials_usage_component1`
    FOREIGN KEY (`component_id`)
    REFERENCES `mydb`.`components` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materials_usage_materials1`
    FOREIGN KEY (`materials_id`)
    REFERENCES `mydb`.`materials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materials_usage_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`suppliers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address1` VARCHAR(45) NULL,
  `address2` VARCHAR(45) NULL,
  `address3` VARCHAR(45) NULL,
  `notes` TINYTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`purchase_order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchase_order_status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`purchase_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchase_orders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `notes` VARCHAR(45) NULL,
  `suppliers_id` INT NOT NULL,
  `purchase_order_status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchase_orders_suppliers1_idx` (`suppliers_id` ASC),
  INDEX `fk_purchase_orders_purchase_order_status1_idx` (`purchase_order_status_id` ASC),
  CONSTRAINT `fk_purchase_orders_suppliers1`
    FOREIGN KEY (`suppliers_id`)
    REFERENCES `mydb`.`suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_orders_purchase_order_status1`
    FOREIGN KEY (`purchase_order_status_id`)
    REFERENCES `mydb`.`purchase_order_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`purchase_order_line_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchase_order_line_items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `qty` INT NOT NULL,
  `materials_id` INT UNSIGNED NOT NULL,
  `purchase_orders_id` INT NOT NULL,
  PRIMARY KEY (`id`, `purchase_orders_id`),
  INDEX `fk_purchase_order_line_items_materials1_idx` (`materials_id` ASC),
  INDEX `fk_purchase_order_line_items_purchase_orders1_idx` (`purchase_orders_id` ASC),
  CONSTRAINT `fk_purchase_order_line_items_materials1`
    FOREIGN KEY (`materials_id`)
    REFERENCES `mydb`.`materials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_order_line_items_purchase_orders1`
    FOREIGN KEY (`purchase_orders_id`)
    REFERENCES `mydb`.`purchase_orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`operation_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`operation_types` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `UnitOfMeasure` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`operations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`operations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  `cost_price` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `markup_percent` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `sale_price` VARCHAR(45) GENERATED ALWAYS AS (cost_price * (1 + (markup_percent / 100))) COMMENT 'generated field sale_price cost + markup',
  `operation_types_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_operations_operation_types1_idx` (`operation_types_id` ASC),
  CONSTRAINT `fk_operations_operation_types1`
    FOREIGN KEY (`operation_types_id`)
    REFERENCES `mydb`.`operation_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`default_operations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`default_operations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL,
  `material_types_id` INT NOT NULL,
  `operations_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_default_operations_material_types1_idx` (`material_types_id` ASC),
  INDEX `fk_default_operations_operations1_idx` (`operations_id` ASC),
  CONSTRAINT `fk_default_operations_material_types1`
    FOREIGN KEY (`material_types_id`)
    REFERENCES `mydb`.`material_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_default_operations_operations1`
    FOREIGN KEY (`operations_id`)
    REFERENCES `mydb`.`operations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`operations_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`operations_log` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL DEFAULT CURRENT_DATETIME,
  `qty` INT NOT NULL DEFAULT 0,
  `components_id` INT UNSIGNED NOT NULL,
  `operations_id` INT NOT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_operations_log_components1_idx` (`components_id` ASC),
  INDEX `fk_operations_log_operations1_idx` (`operations_id` ASC),
  INDEX `fk_operations_log_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_operations_log_components1`
    FOREIGN KEY (`components_id`)
    REFERENCES `mydb`.`components` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_operations_log_operations1`
    FOREIGN KEY (`operations_id`)
    REFERENCES `mydb`.`operations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_operations_log_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`customer_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer_contacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `mobile` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `customers_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_contacts_customers1_idx` (`customers_id` ASC),
  CONSTRAINT `fk_customer_contacts_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `mydb`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`supplier_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`supplier_contacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `mobile` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `suppliers_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_supplier_contacts_suppliers1_idx` (`suppliers_id` ASC),
  CONSTRAINT `fk_supplier_contacts_suppliers1`
    FOREIGN KEY (`suppliers_id`)
    REFERENCES `mydb`.`suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
